package oauth

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// KeySize is the size of the encryption key (AES-256).
const KeySize = 32

// sealer encrypts the wiki credentials in the store and the pending authorization requests in the sign-in form
// with AES-256-GCM. The purpose is authenticated with the data, so a sealed value cannot be used for another one.
type sealer struct {
	aead cipher.AEAD
}

func newSealer(key []byte) (*sealer, error) {
	if len(key) != KeySize {
		return nil, fmt.Errorf("the encryption key must have %d bytes, has %d", KeySize, len(key))
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	aead, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}
	return &sealer{aead: aead}, nil
}

func (s *sealer) seal(plaintext []byte, purpose string) []byte {
	nonce := make([]byte, s.aead.NonceSize())
	_, _ = rand.Read(nonce)
	return s.aead.Seal(nonce, nonce, plaintext, []byte(purpose))
}

func (s *sealer) open(sealed []byte, purpose string) ([]byte, error) {
	n := s.aead.NonceSize()
	if len(sealed) < n {
		return nil, errors.New("sealed value too short")
	}
	return s.aead.Open(nil, sealed[:n], sealed[n:], []byte(purpose))
}

// randomToken returns a random URL-safe token of 32 bytes with a prefix telling its kind (handy in logs and for
// secret scanners).
func randomToken(prefix string) string {
	b := make([]byte, 32)
	_, _ = rand.Read(b)
	return prefix + base64.RawURLEncoding.EncodeToString(b)
}

func hashToken(token string) string {
	sum := sha256.Sum256([]byte(token))
	return hex.EncodeToString(sum[:])
}

func equalHash(a, b string) bool {
	return subtle.ConstantTimeCompare([]byte(a), []byte(b)) == 1
}

// pkceS256 is the S256 code challenge of a PKCE verifier (RFC 7636).
func pkceS256(verifier string) string {
	sum := sha256.Sum256([]byte(verifier))
	return base64.RawURLEncoding.EncodeToString(sum[:])
}

// minPassphrase is the shortest passphrase accepted instead of a key.
const minPassphrase = 32

// ParseKey decodes an encryption key given as 64 hex digits or as base64 (standard or URL alphabet) of 32 bytes. A
// longer random text, such as a password generated by BOSH or CredHub, is accepted too: the key is its SHA-256.
func ParseKey(s string) ([]byte, error) {
	s = strings.TrimSpace(s)
	if b, err := hex.DecodeString(s); err == nil && len(b) == KeySize {
		return b, nil
	}
	for _, enc := range []*base64.Encoding{base64.StdEncoding, base64.RawStdEncoding, base64.URLEncoding, base64.RawURLEncoding} {
		if b, err := enc.DecodeString(s); err == nil && len(b) == KeySize {
			return b, nil
		}
	}
	if len(s) >= minPassphrase {
		sum := sha256.Sum256([]byte(s))
		return sum[:], nil
	}
	return nil, fmt.Errorf("the encryption key must be %d bytes as 64 hex digits or base64, or a random text of at least %d characters",
		KeySize, minPassphrase)
}

// LoadOrCreateKey reads the key from path, or creates the file with a new random key when it does not exist.
func LoadOrCreateKey(path string) (key []byte, created bool, err error) {
	b, err := os.ReadFile(path)
	if err == nil {
		key, err = ParseKey(string(b))
		if err != nil {
			return nil, false, fmt.Errorf("%s: %w", path, err)
		}
		return key, false, nil
	}
	if !errors.Is(err, os.ErrNotExist) {
		return nil, false, err
	}
	key = make([]byte, KeySize)
	if _, err := rand.Read(key); err != nil {
		return nil, false, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return nil, false, err
	}
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return nil, false, err
	}
	if _, err := f.WriteString(hex.EncodeToString(key) + "\n"); err != nil {
		_ = f.Close()
		return nil, false, err
	}
	return key, true, f.Close()
}
